### ISSUE TITLE
H812 Nougat - HD Video Playback low framerate, stuttering, slow playback speed

### ISSUE THREAD

**Issue by vsTerminus** [Suicide-Squirrel/issues_oreo#11]
I don't know it this is related to #10 or not, so I opened a separate issue for it. Again this seems to be H812 only - unlocked by way of UsU.

Basically, high definition video playback is choppy and slow. This seems to affect literally everything. YouTube and Twitch are smooth up to 480p, but at 720p or above they get slow and choppy. Audio plays fine, but video does not. Reducing the quality back to 480p results in video catching up and playing smoothly again.

I've noticed this with YouTube, Twitch, SnapChat, Funimation, and a few others.

It also affects local video playback. I have done less testing here, but 1080p AVC files behave the same, choppy and slow, while 720p HEVC seemed to be working OK. I will need to do more testing with local files.

I do not have a log to attach here because I haven't performed a "clean" test - If I got you a logcat now it would have xposed and a shit ton of apps in it and I suspect you'd just ignore it entirely. Let me know what you need to help diagnose this one and I will make it happen.

**Comment by steadfasterX** [comment]
Sorry didn't realized that you spoke about N. Do you have you the same issues on O?

**Comment by the-nummer-zone** [comment]
Something similar is happening to me on RR Oreo, where I am unable to play 60fps video on my h812.

**Comment by steadfasterX** [comment]
Ok just to let you know: I will focus only on LOS. Kessaras on aoscp 
and we all do only oreo. There will be not further development for N.
RR may never get further updates or even newer release as this is nothing we three use.

**Comment by the-nummer-zone** [comment]
They all use same sources, so what's to happen on aoscp is bound to happen on RR

**Comment by steadfasterX** [comment]
That's not true sorry. I know what you mean because it's true that they share the same sources in many parts. So far so good but each of these candidates have their own repos their own Forks of something which they modify. so you can not say they are identical and of course they can behave different and of course development or bug fixing may be different because of this fact

**Comment by vsTerminus** [comment]
So I updated to LineageOS 15.1 Oreo yesterday with the new H812 build. I posted my findings [on XDA](https://forum.xda-developers.com/showpost.php?p=76874949&postcount=7), but for anyone watching just this, **yes**, I still have the issue on Oreo. It's *better* than it was on Nougat, but still problematic.

Here's the gist: 30fps video is working up to 1080p, 60fps video is not.

- 480p or below works fine
- 720p (30fps) seems to work ok
- 1080p (30fps) stutters a little bit but overall seems to be ok too now
- 1440p (30fps) stutters a lot, slow playback rate.
- 720p (60fps) video plays then freezes, then plays, then freezes, repeat
- 1080p (60fps) video freezes and largely does not play at all.

Audio is always fine, it's just video that has issues.

The experience is identical in both YouTube and Twitch. I haven't tested other sources yet.

**Comment by steadfasterX** [comment]
ok guys I got some news about that thing here.
a while ago the XDA user [Triuomo](https://forum.xda-developers.com/member.php?u=8854963) send me a TWRP flashable file which fixed the lags for him. Unfortunately I hadn't the time to test or share it yet. I have optimized his initial version a bit and here it goes:

1. create a backup of your **system** partition 
1. flash it
1. report back if that fixes your issue

# warning 

Some users reporting currently that they have issues connecting the camera after installing this patch. At the moment it is completely unclear why and if if you are scared to lose your camera forever do not flash it yet. If you have flashed it already and encountering issues provide a logcat when starting the camera. See my signature on XDA for the exact how to.

-file removed-

**Comment by rundumdieuhr** [comment]
> 1. create a backup of your **system** partition
> 2. flash it
> 3. report back if that fixes your issue

Thanks so much! Having flashed it, no problems with video playback in-app/in-browser. Tested 360p/540p/720p/1080p (possibly slighter framerate with 1080p? but no lags). 
Is this already in lineage-15.1-20190409-UNOFFICIAL-h815.zip?

Edit: Worked at first. In the meantime, I am encountering camera, audio and phone call problems despite wipe/clean flash. Ooops... 
Any forum where the users you mention have been discussing the issue or where I could provide logs?

**Comment by steadfasterX** [comment]
No this is just an experimental test and so is not included in any ROM at the moment. See my updated comment above

**Comment by rundumdieuhr** [comment]
Please find a camera logcat (camera not connected / unavailable) at 
https://drive.google.com/file/d/13NMC2DIiSUHSf-BkNxIXs0NkFM0K2PP4/

**Comment by steadfasterX** [comment]
Do you even read my warning above before flashing ? :p

**Comment by steadfasterX** [comment]
@thsachs 

Try to set selinux to permissive . 

su 
setenforce permissive 
getenforce 
stop cameraserver 
start cameraserver 

Try opening cam again

**Comment by rundumdieuhr** [comment]
> Try to set selinux to permissive .
> 
> su
> setenforce permissive
> getenforce
> stop cameraserver
> start cameraserver
> 
> Try opening cam again

Thanks for your heads up. I'll give it a try.
--Edit: Did so. Restarting the cameraserver in permissive mode worked, yet it didn't change the behaviour. I amended the log https://drive.google.com/file/d/13NMC2DIiSUHSf-BkNxIXs0NkFM0K2PP4/.

> Do you even read my warning above before flashing ? :p

Directed to me? :p I am the same person who flashed yesterday morning before you edited to warn...

**Comment by steadfasterX** [comment]
Ok try the same but now also with 

stop sensors 
start sensors 

and provide the logcat again. I think I need my hands on the device which requires FWUL .. Do you have it ?
Not before Monday though ..

**Comment by rundumdieuhr** [comment]
Thank you for following up and helping out! I have done as instructed and replaced the log. No change here. Any camera and audio (incl. phone) connection remains broken, unfortunately. Excuse my little knowledgeable feeling, my hopes in improvement aren't high. I tried everything I am capable of: restoring the system partition backup first. When the issue remained, I wiped and clean flashed LOS several times. That should rule out any service/software error, shouldn't it? I am afraid my G4's mainboard has been affected.
You are welcome to diagnose yourself next week. No hurries. I don't have FWUL but Ubuntu linux.

**Comment by steadfasterX** [comment]
discussion going on here: https://forum.xda-developers.com/g4/development/rom-lineageos-15-1-t3806615

**Comment by rundumdieuhr** [comment]
> discussion going on here: https://forum.xda-developers.com/g4/development/rom-lineageos-15-1-t3806615

Thanks for the forum link and your diagnosis there. That makes 3 affected users and confirms my feeling. :( I don't blame you and appreciate you taking a further look into it, if any functionality can be restored. Let me know if you need to play with my device from remote. Anyway, I've placed the order for a replacement device, as I was using the G4 on a daily basis as well. Shit happens... I am not signed up on xda-dev, but I'll follow reading there.

**Comment by steadfasterX** [comment]
if you can contact me on Telegram (username StEaDfX)

**Comment by steadfasterX** [comment]
> > discussion going on here: https://forum.xda-developers.com/g4/development/rom-lineageos-15-1-t3806615
> 
> Thanks for the forum link and your diagnosis there. That makes 3 affected users and confirms my feeling. :( I don't blame you and appreciate you taking a further look into it, if any functionality can be restored. Let me know if you need to play with my device from remote. Anyway, I've placed the order for a replacement device, as I was using the G4 on a daily basis as well. Shit happens... I am not signed up on xda-dev, but I'll follow reading there.

you should have received my TG name by notification mail on that issue (hopefully). If not let me know..
If you have no TG account you can use the IRC webchat to contact me as well:

http://webchat.freenode.net/?channels=Carbonfusion-user

**Comment by steadfasterX** [comment]
@thsachs let me know when you have time to test my new fix.. (IRC is fine)

**Comment by steadfasterX** [comment]
## READ ME

ok so here comes the fix for the fix.. :p 

I have tested this on my personal device (so bricked it to fix it) and everything works again with my new patch.
It also should be considered safe to flash for all UsU'd devices but well there is still a risk that another model behaves different then others... so if you take the risk its your choice (as usual).

The new patch comes as a [7zip](https://www.7-zip.org/) compressed file to make it clear that you must extract it first (yea even when the file name is obvious but...).

**LG-G4_VideoLag-Fix_EXTRACTME-AND-READ-THE-README.7z contains:** 
|
|--- README.txt
|--- LG-G4_VideoLag-Fix_increases-adsp-and-venus-to-arb2.zip
|--- LG-G4_VideoLag-Fix_increases-adsp-and-venus-to-arb2.zip.md5


### Installing the patch

Obviously you should READ the README first. It contains important information and background details.

Once you have read and **100% understood** the README.txt go on:

1. If you have flashed the previous patch file: flash the current ROM again!! This step is CRUCIAL important - do not skip it! If you never applied such a patch go on with the next step instead.
1. Next do a backup of both: **system** & **modem** with TWRP (SALT works too but is not needed here)
1. Now copy the files _LG-G4_VideoLag-Fix_increases-adsp-and-venus-to-arb2.zip_ and _LG-G4_VideoLag-Fix_increases-adsp-and-venus-to-arb2.zip.md5_ to your phone (while still in TWRP)
1. flash _LG-G4_VideoLag-Fix_increases-adsp-and-venus-to-arb2.zip_ in TWRP 
(leave "_ZIP signature checking_" **UNCHECKED** )
1. reboot and check that: camera, sound, cell service, videos are working as they should

### Download

http://leech.binbash.rocks:8008/misc/ 
(file: LG-G4_VideoLag-Fix_EXTRACTME-AND-READ-THE-README.7z)
