### ISSUE TITLE
Torch tile is not working

### ISSUE THREAD

**Issue by steadfasterX** [Suicide-Squirrel/issues_oreo#14]
## Workaround
 
https://play.google.com/store/apps/details?id=com.umang96.flashlight

**Comment by tcgm** [comment]
Workaround installs a second Flashlight tile but does not actually fix this issue on H811. The second tile and the app can't toggle the flashlight either.

**Comment by speed47** [comment]
The bug is also present on AICP (as expected, as it's based on LOS).
The workaround link no longer works, however I can confirm that the following app does work correctly (you must be rooted however):
https://play.google.com/store/apps/details?id=io.github.berkantkz.kztorch
Just remove the default torch tile, and replace it by the one provided by this app.

**Comment by pixapo** [comment]
It does not work on my h815 :(

**Comment by szilm** [comment]
h815 and torch doesn't work from tile or long-press power button.  Camera flashes normally.

**Comment by ghost** [comment]
camera/QCamera2/QCamera2Hal.cpp:53:.set_torch_mode         = NULL

Looks like it was never updated. 

It probably should look like: https://github.com/LineageOS/android_device_oneplus_oneplus2/blob/lineage-15.1/camera/QCamera2/QCamera2Hal.cpp

**Comment by pavlaras** [comment]
no.
good point but its the exact opposite.
it was disabled https://github.com/CypherOS/hardware_qcom_camera/commit/16c6afd5429aa85e325654e5c9711659203f58bd

**Comment by pavlaras** [comment]
> camera/QCamera2/QCamera2Hal.cpp:53:.set_torch_mode = NULL
> 
> Looks like it was never updated.
> 
> It probably should look like: https://github.com/LineageOS/android_device_oneplus_oneplus2/blob/lineage-15.1/camera/QCamera2/QCamera2Hal.cpp

at that link if you go back 1step you will see this:
https://github.com/LineageOS/android_device_oneplus_oneplus2/blob/5882117e8c33b21ffa49d2283f76cdd1aa30bbb3/camera/QCamera2/Android.mk#L87
This means that they build their camera hal. And here you see the call for building it: https://github.com/LineageOS/android_device_oneplus_oneplus2/blob/5882117e8c33b21ffa49d2283f76cdd1aa30bbb3/device.mk#L121
Ours is prebuild. I don't build it because it doesn't work at all. It never worked. Since LP we use prebuilt camera hal from LG. So there is no way to edit it.
Also that means that it was never removed in our camera hal.
So, good guess there, but it must have been removed from somewhere else too.

**Comment by Bullnados** [comment]
Link in first post is not working

**Comment by pavlaras** [comment]
> ## Workaround
> https://play.google.com/store/apps/details?id=com.umang96.flashlight

https://mega.nz/#!h9w0gY7Z!_FiXQo49OvETSwH22SAhmss2oXFXeYUKi_RCMjzwDqs

**Comment by steadfasterX** [comment]
workaround has been backported (at least for LOS):

https://github.com/Suicide-Squirrel/android_device_lge_g4-common/commit/c26e0cb201d3ab09c81aeb9795b9c3e20742246d

**Comment by rundumdieuhr** [comment]
Is fixed Pie issue https://github.com/Suicide-Squirrel/issues_pie/issues/8#issuecomment-491868423 portable to Oreo? :)

**Comment by steadfasterX** [comment]
yep. i'm building it rn to test and if that works a new build run for all devices will start (including sec patches ofc)

**Comment by steadfasterX** [comment]
implemented by:

https://github.com/Suicide-Squirrel/android_device_lge_g4-common/commit/37fbc64f3c5f360635c7c52e9b813f425a1d89f8

This solution will work without root, is auto-added to the Quicksettings tile, is working properly even when selinux is enforcing... and so.. I will close that for now. Maybe some day someone find a real fix for that.
