### ISSUE TITLE
Android native screen casting doesn't work

### ISSUE THREAD

**Issue by pavlaras** [Suicide-Squirrel/issues_oreo#7]

**Comment by steadfasterX** [comment]
still relevant? logs needed..

**Comment by rundumdieuhr** [comment]
Yes, relevant for me on H815 / LOS 15.1-20190409-unofficial-h815. Android won't recognize any Miracast device. Will provide logs as soon as I can! (Not urgent for me though.)

Edit: logcast.txt is now online ;) Available for steadfasterX (post if anyone else needs it, so I would make it public): https://drive.google.com/file/d/1Z7hQiQYaw8-BOM3dfyooxTjnUMv-LsUG/view?usp=sharing
What happened: Searched for streaming device yielded no results. While searching, I had two Miracast devices (Fire TV stick, LG WebOS SmartTV) ready with the according streaming page open.

**Comment by rundumdieuhr** [comment]
#remainopen Please don't stale or close, botty. ;) I would love any progress on the Miracast issue and totally am willing to contribute. Of course only when convenient to steadfasterX as the developer whose efforts I highly appreciate - there is no hurry.

**Comment by steadfasterX** [comment]
I prefer logs attached to the case so added the one from here https://github.com/Suicide-Squirrel/issues_oreo/issues/7#issuecomment-487919248 to this comment : 
[logcast.txt](https://github.com/Suicide-Squirrel/issues_oreo/files/3766086/logcast.txt)

the chance that I will work on this issue is likely zero though, sorry.

**Comment by rundumdieuhr** [comment]
> I prefer logs attached to the case so added the one from here [#7 (comment)](https://github.com/Suicide-Squirrel/issues_oreo/issues/7#issuecomment-487919248) to this comment :
> logcast.txt
> 
> the chance that I will work on this issue is likely zero though, sorry.

Ok if it slightly improves the chance of you looking into the issue. ;) Otherwise, we had talked about this in summer, I preferred sharing the log with you privately in case it contains any sensitive information. So if you do not plan on working on it (which is ok), I cannot see the reason for publishing it. :)
Anyway, keep up the great work & thank you. I am on LOS 16 now for the time bei and will assist in testing the similar issue there.
